# server settings
server:
  port: $port
  servlet.context-path: $contextPath

#log output file
logging:
  file.path: $logspath/logs_${HOSTNAME}/
  level:
    root: INFO

#PX drop box details
px:
  ftp.server:
    address: ftp-pride-private.ebi.ac.uk
    port: 21
  aspera.server:
    address: hx-fasp-1.ebi.ac.uk
    port: 3301
  drop.box:
    one:
      directory: $dropBoxOneDirectory
      user: $dropBoxOneUser
      password: $dropBoxOnePassword
    two:
      directory: $dropBoxTwoDirectory
      user: $dropBoxTwoUser
      password: $dropBoxTwoPassword
    three:
      directory: $dropBoxThreeDirectory
      user: $dropBoxThreeUser
      password: $dropBoxThreePassword
    four:
      directory: $dropBoxFourDirectory
      user: $dropBoxFourUser
      password: $dropBoxFourPassword
    five:
      directory: $dropBoxFiveDirectory
      user: $dropBoxFiveUser
      password: $dropBoxFivePassword
  submission.queue.dir: $submissionQueueDir
  notification.email:
    to: $emailTo
    subject: $emailSubject
    host: $emailHost
  web.url: http://www.proteomexchange.org

#pride-repo-ws
app.name: $app_name
pride-repo.api:
  baseUrl: $repo_api_base_url
  keyName: $repo_api_key_name
  keyValue: $repo_api_key_value

