# server settings
server:
  port: $port
  servlet.context-path: $contextPath

#log output file
logging:
  config: logback/logback-spring.xml
  level:
    root: INFO

management.health.mail.enabled: false

#PX drop box details
px:
  ftp.server:
    address: ftp-pride-private.ebi.ac.uk
    port: 21
  aspera.server:
    address: hx-fasp-1.ebi.ac.uk
    port: 3301
  drop.box:
    five:
      directory: $dropBoxFiveDirectory
      user: $dropBoxFiveUser
      password: $dropBoxFivePassword
  submission:
    mount.path: $submission_vol_path
  notification.email:
    to: $emailTo
    subject: $emailSubject
    host: $emailHost
  web.url: http://www.proteomexchange.org


submission-api:
  login-url: $submission_api_login_url
  validation-url: $submission_api_validation_url
  user: $submission_api_user
  password: $submission_api_password
proxy-host: $http_proxy_host
proxy-port: $http_proxy_port


#pride-repo-ws
app.name: $app_name
pride-repo.api:
  baseUrl: $repo_api_base_url
  keyName: $repo_api_key_name
  keyValue: $repo_api_key_value


